CREATE TABLE TICKETS (
    TICKET_ID NUMBER PRIMARY KEY,
    DNI VARCHAR2(9) NOT NULL,
    PRICE NUMBER(5,2) NOT NULL,
    DATESTARTVALIDITY DATE NOT NULL,
    DATEENDVALIDITY DATE NOT NULL
);

CREATE TABLE ACCOUNTS (
    ACCOUNTID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    LANGUAGE NVARCHAR2(20) NOT NULL
);

CREATE TABLE DISCOUNTS (
    DISCOUNTID NUMBER PRIMARY KEY,
    DISCOUNTNAME VARCHAR2(20) NOT NULL,
    PERCENTAGE NUMBER NOT NULL
);

CREATE TABLE CONTRACTS (
    CONTRACTID NUMBER PRIMARY KEY,
    STARTDATE DATE NOT NULL,
    FINISHDATE DATE NOT NULL,
    BASESALARY NUMBER(6,2) NOT NULL,
    EXTRA_PERCENT NUMBER NOT NULL,
    HOURS NUMBER NOT NULL,
    BANKACCOUNT VARCHAR2(20) NOT NULL
);

CREATE TABLE SECTIONS (
    SectionID INTEGER PRIMARY KEY,
    SectionName VARCHAR2(100) NOT NULL,
    Sizes INTEGER NOT NULL,
    Visitors INTEGER
);

CREATE TABLE PRODUCTS (
    ProductID NUMBER PRIMARY KEY,
    ProductName NVARCHAR2(100) NOT NULL,
    Price NUMBER(6,2) NOT NULL,
    ExpirationDate DATE
);

CREATE TABLE EMPLOYEES (
    EmployeeID NUMBER PRIMARY KEY,
    DNI VARCHAR2(9) NOT NULL,
    Name NVARCHAR2(100) NOT NULL,
    Surname NVARCHAR2(100) NOT NULL,
    Gender NVARCHAR2(20) NOT NULL,
    DateFirstContract DATE NOT NULL,
    Email NVARCHAR2(50) NOT NULL,
    TelefoneNumber NUMBER NOT NULL,
    Street NVARCHAR2(100) NOT NULL,
    Location NVARCHAR2(100) NOT NULL,
    ContactDNI VARCHAR2(9) NOT NULL
);

CREATE TABLE EMERGENCYCONTACTS (
    DNI VARCHAR2(9) PRIMARY KEY,
    PhoneNumber NUMBER NOT NULL,
    FullName NVARCHAR2(100) NOT NULL
);

CREATE TABLE ANIMALS (
    AnimalID NUMBER PRIMARY KEY,
    Species NVARCHAR2(100) NOT NULL,
    Sex NVARCHAR2(20) NOT NULL,
    Weight NUMBER NOT NULL,
    Birthdate DATE NOT NULL,
    TimeAtTheZoo NUMBER NOT NULL,
    MorningFood NVARCHAR2(100) NOT NULL,
    NightFood NVARCHAR2(100) NOT NULL,
    Medicine NVARCHAR2(100) NOT NULL,
    DateOfArrival DATE NOT NULL
);

CREATE TABLE ROUTES (
    RouteID NUMBER PRIMARY KEY,
    RouteName NVARCHAR2(100) NOT NULL,
    EstimatedLengthTime NUMBER NOT NULL,
    StartHour TIMESTAMP NOT NULL,
    SectionID NUMBER,
    CONSTRAINT fk_RoutesSec FOREIGN KEY (SectionID) REFERENCES SECTIONS(SectionID)
);

CREATE TABLE VIPPASSES (
    TICKET_ID NUMBER PRIMARY KEY NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID)
);

CREATE TABLE PAYMENTMETHODS (
    ACCOUNTID NUMBER PRIMARY KEY NOT NULL,
    PAYMENTMETHOD NVARCHAR2(20) NOT NULL,
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID)
);

CREATE TABLE DAYS (
    CONTRACTID NUMBER PRIMARY KEY NOT NULL,
    DAYS NVARCHAR2(20) NOT NULL,
    FOREIGN KEY (CONTRACTID) REFERENCES CONTRACTS(CONTRACTID)
);

CREATE TABLE SHOPS (
    ShopID NUMBER PRIMARY KEY,
    ShopName NVARCHAR2(100) NOT NULL,
    SectionID NUMBER,
    CONSTRAINT ShopSection FOREIGN KEY (SectionID) REFERENCES SECTIONS(SectionID)
);

CREATE TABLE ENCLOSURES (
    EnclosureID CHAR(5) PRIMARY KEY,
    Species NVARCHAR2(200),
    EnclosureFloorMaterial NUMBER NOT NULL,
    DateLastInspection DATE,
    DateNextInspection DATE NOT NULL,
    SectionID NUMBER,
    CONSTRAINT EnclosureSection FOREIGN KEY (SectionID) REFERENCES SECTIONS(SectionID)
);

CREATE TABLE PARENTS (
    AnimalID NUMBER PRIMARY KEY,
    ParentID NUMBER NOT NULL,
    CONSTRAINT fk_Parent_Animal FOREIGN KEY (AnimalID) REFERENCES ANIMALS(AnimalID),
    CONSTRAINT fk_Parent_Parent FOREIGN KEY (ParentID) REFERENCES ANIMALS(AnimalID)
);

CREATE TABLE ACCTIC (
    TICKET_ID NUMBER NOT NULL,
    ACCOUNTID NUMBER NOT NULL,
    PRIMARY KEY (TICKET_ID, ACCOUNTID),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID)
);

CREATE TABLE SHO_PRO (
    ShopID NUMBER,
    ProductID NUMBER,
    PRIMARY KEY (ShopID, ProductID),
    FOREIGN KEY (ShopID) REFERENCES SHOPS(ShopID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID)
);

CREATE TABLE ENCLOSUREITEMS (
    EnclosureitemID NUMBER PRIMARY KEY,
    Nombre NVARCHAR2(100) NOT NULL,
    EnclosureID CHAR(5),
    FOREIGN KEY (EnclosureID) REFERENCES ENCLOSURES(EnclosureID)
);

CREATE TABLE GUIDEDENTRIES (
    TICKET_ID NUMBER PRIMARY KEY NOT NULL,
    ROUTES_ID NUMBER,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
    FOREIGN KEY (ROUTES_ID) REFERENCES ROUTES(RouteID)
);

CREATE TABLE SECURITYEMPLOYEES (
    EmployeeID NUMBER PRIMARY KEY,
    Shift NVARCHAR2(20) NOT NULL,
    ExtraHoures NUMBER NOT NULL,
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID)
);

CREATE TABLE CLEANERS (
    EmployeeID NUMBER PRIMARY KEY,
    FOREIGN KEY (EmployeeID) REFERENCES SECURITYEMPLOYEES(EmployeeID)
);

CREATE TABLE SHOPKEEPERS (
    EmployeeID NUMBER PRIMARY KEY,
    ShopID NUMBER,
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID),
    FOREIGN KEY (ShopID) REFERENCES SHOPS(ShopID)
);

CREATE TABLE VETERINARIES (
    EmployeeID NUMBER PRIMARY KEY,
    FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID)
);
