CREATE TABLE TICKETS (
    "TICKET_ID" INTEGER PRIMARY KEY IDENTITY(1,1),
    "DNI" VARCHAR(9) NOT NULL ENEABLE,
    "PRICE" Decimal(5,2) NOT NULL ENEABLE,
    "DATESTARTVALIDITY" DATE NOT NULL ENEABLE,
    "DATEENDVALIDITY" DATE NOT NULL ENEABLE
);

CREATE TABLE VIPPASSES (
    "TICKET_ID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    FOREING KEY ("TICKET_ID") REFERENCES TICKETS("TICKET_ID")
);

CREATE TABLE GUIDEDENTRIES (
    "TICKET_ID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    FOREING KEY ("TICKET_ID") REFERENCES TICKETS("TICKET_ID"),
    FOREIGN KEY ("ROUTES_ID") REFERENCES ROUTES("ROUTES_ID")
);

CREATE TABLE ACCOUNTS (
    "ACCOUNTID" INTEGER PRIMARY KEY IDENTITY(1,1),
    "EMAIL" VARCHAR(50) NOT NULL ENEABLE,
    "USERNAME" VARCHAR(50) NOT NULL ENEABLE,
    "BIRTHDATE" DATE NOT NULL ENEABLE,
    "LANGUAGE" NVARCHAR(20) NOT NULL ENEABLE
);

CREATE TABLE ACCTIC (
    "TICKET_ID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    "ACCOUNTID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    FOREIGN KEY ("TICKET_ID") REFERENCES TICKETS("TICKET_ID"),
    FOREIGN KEY ("ACCOUNTID") REFERENCES ACCOUNTS("ACCOUNTID")
);

CREATE TABLE PAYMENTMETHODS (
    "ACCOUNTID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    "PAYMENTMETHOD" NVARCHAR(20) NOT NULL ENEABLE,
    FOREIGN KEY ("ACCOUNTID") REFERENCES ACCOUNTS("ACCOUNTID")
);

CREATE TABLE DISCOUNTS (
    "DISCOUNTID" INTEGER PRIMARY KEY IDENTITY(1,1),
    "DISCOUNTNAME" VARCHAR(20) NOT NULL ENEABLE,
    "PERCENTAGE" INTEGER NOT NULL ENEABLE
);

CREATE TABLE CONTRACTS (
    "CONRACTID" INTEGER PRIMARY KEY IDENTITY(1,1),
    "STARTDATE" DATE NOT NULL ENEABLE,
    "FINISHDATE" DATE NOT NULL ENEABLE,
    "BASESALARY" DECIMAL(6,2) NOT NULL ENEABLE, /* si alguien cobra mas de 6 cifras al mes da miedo, tampoco se si este sueldo es mensual o anual, entiendo qe mensual */
    "EXTRA%" INTEGER NOT NULL ENEABLE,
    "HOURES" INTEGER NOT NULL ENEABLE,
    "BANKACCOUNT" VARCHAR(20) NOT NULL ENEABLE,
);

CREATE TABLE DAYS (
    "CONTRACTID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    "DAYS" NVARCHAR(20) NOT NULL ENEABLE,
    FOREIGN KEY ("CONTRACTID") REFERENCES CONTRACTS("CONTRACTID")
);

CREATE TABLE EMPCON (
    "EMPLOYEEID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    "CONTRACTID" INTEGER PRIMARY KEY NOT NULL ENEABLE,
    "BONUSPAY" DECIMAL(6,2) NOT NULL ENEABLE,
    "EXTRAHOURSPAY" DECIMAL NOT NULL ENEABLE,
    FOREIGN KEY ("EMPLOYEEID") REFERENCES EMPLOYEES("EMPLOYEEID"),
    FOREIGN KEY ("CONTRACTID") REFERENCES CONTRACTS("CONTRACTID")
);

/* Entiendo que me falta algo para las candidateKey pero no se como ponerloni he encontrado nada el los ejemplos */


