CREATE DATABASE ZooDatabase;
GO

USE zoosDatabase;
GO

CREATE TABLE TICKETS (
    TICKET_ID INT PRIMARY KEY,
    DNI VARCHAR(9) NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL DEFAULT '15.00',
    DATESTARTVALIDITY DATE NOT NULL,
    DATEENDVALIDITY DATE NOT NULL
);

CREATE TABLE ACCOUNTS (
    ACCOUNTID INT PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    BIRTHDATE DATE NOT NULL CHECK (BIRTHDATE >= '2007-01-01'),
    LANGUAGE NVARCHAR(20) NOT NULL DEFAULT "SPANISH"
);

CREATE TABLE DISCOUNTS (
    DISCOUNTID INT PRIMARY KEY,
    DISCOUNTNAME VARCHAR(50) NOT NULL,
    PERCENTAGE INT NOT NULL DEFAULT '20' CHECK (PERCENTAGE >= 5),
    CONSTRAINT FK_DISACCTIC FOREIGN KEY (DISCOUNTID) REFERENCES ACCTIC(DISCOUNTID)
);

CREATE TABLE CONTRACTS (
    CONTRACTID INT PRIMARY KEY,
    STARTDATE DATE NOT NULL,
    FINISHDATE DATE NOT NULL,
    BASESSALARY DECIMAL(6,2) NOT NULL,
    EXTRA_PERCENT INT NOT NULL DEFAULT '50',
    HOURS INT NOT NULL,
    BANKACCOUNT VARCHAR(24) NOT NULL
);

CREATE TABLE SECTIONS (
    SECTIONID INT PRIMARY KEY,
    SECTIONNAME VARCHAR(100) NOT NULL,
    DIMENSION INT NOT NULL,ILL
    PHONENUMBER INT NOT NULL,
    FILLNAME NVARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCTS (
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL DEFAULT '10.00' CHECK (PRICE <= '100.00'),
    EXPIRATIONDATE DATE
);


CREATE TABLE ANIMALS (
    ANIMALID INT PRIMARY KEY,
    NICKNAME VARCHAR(50) NOT NULL
    SPECIES VARCHAR(100) NOT NULL,
    SEX CHAR(1) NOT NULL,
    WIGHT DECIMAL(7,2) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    TIMEATTHEZOO INT NOT NULL,
    MORNINGFOOD VARCHAR(100),
    NIGTHFOOD VARCHAR(100),
    MEDICINE VARCHAR(100),
    DATEOFARRIVAL DATE NOT NULL
);

CREATE TABLE VIPPASSES (
    TICKET_ID INT PRIMARY KEY NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
);

CREATE TABLE PAYMENTMETHODS (
    ACCOUNTID INT PRIMARY KEY,
    PAYMENTMETHOD VARCHAR(20) NOT NULL,
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID)
);

CREATE TABLE DAYS (
    CONTRACTID INT PRIMARY KEY NOT NULL,
    DAYS VARCHAR(20) NOT NULL,
    FOREIGN KEY (CONTRACTID) REFERENCES CONTRACTS(CONTRACTID)
);

CREATE TABLE SHOPS (
    SHOPID INT PRIMARY KEY,
    SHOPNAME VARCHAR(100) NOT NULL,
    SECTIONID INT,
    CONSTRAINT FK_SHOPSECTION FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID)
);

CREATE TABLE ENCLOSURES (
    ENCLOSUREID CHAR(5) PRIMARY KEY,
    SPECIES VARCHAR(200),
    ENCLOSUREFLOORMATERIAL INT NOT NULL,
    DATELASTINSPECTION DATE,
    DATENEXTINSPECTION DATE NOT NULL,
    SQUAREMETERS INT NOT NULL CHECK (SQUAREMETERS >= 5),
    SECURITYLEVEL INT NOT NULL,
    TEMPERATURE INT NOT NULL CHECK (TEMPERATURE >= -10 AND TEMPERATURE <= 40),
    ELECTRICALEXPENSE INT NOT NULL,
    ENVIROMENT VARCHAR(50) NOT NULL,
    HASSHOW BIT NOT NULL DEFAULT '0',
    SECTIONID INT,
    CONSTRAINT FK_ENCLOSURESECTION FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    DNI VARCHAR(9) NOT NULL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL, 
    GENDER CHAR(1) NOT NULL,
    DATEFIRSTCONTRACT DATE NOT NULL,
    BIRTHDATE DATE NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEPHONENUMBER INT NOT NULL,
    ADRESSSTREES VARCHAR(100) NOT NULL,
    ADRESSLOCATION VARCHAR(100) NOT NULL,
    CONTACTDNI VARCHAR(9) NOT NULL,
    CONSTRAINT FK_CONEM FOREIGN KEY (CONTACTDNI) REFERENCES EMERGENCYCONTACTS(DNI)
);

CREATE TABLE EMERGENCYCONTACTS (
    DNI VARCHAR(9) PRIMARY KEY,
    PHONENUMBER INT NOT NULL,
    FULLNAME VARCHAR(100) NOT NULL,
    CONSTRAINT FK_CONEM FOREIGN KEY (DNI) REFERENCES EMPLOYEES(DNI)
);


CREATE TABLE PARENTS (
    ANIMALID INT PRIMARY KEY,
    PARENTID INT,
    CONSTRAINT FK_PARENTS1 FOREIGN KEY (ANIMALID) REFERENCES ANIMALS(ANIMALID),
    CONSTRAINT FK_PARENTS2 FOREIGN KEY (PARENTID) REFERENCES ANIMALS(ANIMALID)
);

CREATE TABLE ILLNESES (
    ANIMALID INT PRIMARY KEY,
    ILLNESSES VARCHAR(100) NOT NULL,
    CONSTRAINT FK_ILLNESSES FOREIGN KEY (ANIMALID) REFERENCES ANIMALS(ANIMALID)
);

CREATE TABLE ROUTES (
    ROUTEID INT PRIMARY KEY,
    ROUTENAME VARCHAR(100) NOT NULL,
    ESTIMATEDLENGTHTIME INT NOT NULL DEFAULT '60' CHECK (ESTIMATEDLENGTHTIME>=15 AND ESTIMATEDLENGTHTIME <= 90),
    STARTHOUR DATE NOT NULL CHECK (STARTHOUR >= '10:00' AND STARTHOUR <= '18:00'),
    SECTIONID INT,
    CONSTRAINT FK_ROUTESSEC FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID)
);

CREATE TABLE ENCLOSUREITEMS (
    ENCLOSUREITEMID INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ENCLOSUREID CHAR(5),
    CONSTRAINT FK_ENCLOSUREENCLOSUREITEM FOREIGN KEY (ENCLOSUREID) REFERENCES ENCLOSURES(ENCLOSUREID)
);

CREATE TABLE SHOPRO (
    SHOPID INT,
    PRODUCTID INT,
    PRIMARY KEY (SHOPID, PRODUCTID),
    CONSTRAINT FK_SHOP FOREIGN KEY (SHOPID) REFERENCES SHOPS(SHOPID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID)
);

CREATE TABLE LANGUAGES (
    EMPLOYEEID INT PRIMARY KEY,
    LANGUAGES VARCHAR(20) NOT NULL,
    CONSTRAINT FK_LANGUAGES FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID)
);

CREATE TABLE SECURITYEMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    SHIFT VARCHAR(20) NOT NULL,
    EXTRAHOURES INT NOT NULL DEFAULT '0',
    CONSTRAINT FK_SECEMP FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID)
);

CREATE TABLE STRUCTURALEMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    SHIFT VARCHAR(20) NOT NULL,
    EXTRAHOURES INT NOT NULL,
    CONSTRAINT FK_STREMP FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID)
);

CREATE TABLE ANIMALEMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    CONSTRAINT FK_ANIEMP FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID)
);

CREATE TABLE GUARD (
    EMPLOYEEID INT PRIMARY KEY,
    RANK VARCHAR(20) NOT NULL,
    CONSTRAINT FK_GUARD FOREIGN KEY (EMPLOYEEID) REFERENCES SECURITYEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE ACCTIC (
    TICKET_ID INT NOT NULL,
    ACCOUNTID INT NOT NULL,
    DISCOUNTID INT NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID),
    PRIMARY KEY (TICKET_ID, ACCOUNTID)
);

CREATE TABLE SHOPROSEC (
    SHOPID INT,
    PRODUCTID INT,
    SECTIONID INT,
    PRIMARY KEY (SHOPID, PRODUCTID, SECTIONID),
    CONSTRAINT FK_SHOPRO FOREIGN KEY (SHOPID, PRODUCTID) REFERENCES SHOPRO(SHOPID, PRODUCTID),
    CONSTRAINT FK_SECTION FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID) 
);

CREATE TABLE ENCANI (
    ENCLOSUREID CHAR(5) PRIMARY KEY,
    SPECIES VARCHAR(100) NOT NULL,
    POPULATION INT NOT NULL CHECK (POPULATION <= 15),
    ANIMALID INT,
    CONSTRAINT FK_ENCANIENC FOREIGN KEY (ENCLOSUREID) REFERENCES ENCLOSURES(ENCLOSUREID),
    CONSTRAINT FK_ENCANIANI FOREIGN KEY (ANIMALID) REFERENCES ANIMALS(ANIMALID)
);

CREATE TABLE SURVEILLANCE (
    EMPLOYEEID INT PRIMARY KEY,
    CONSTRAINT FK_SURVEILLANCE FOREIGN KEY (EMPLOYEEID) REFERENCES GUARD(EMPLOYEEID)
);

CREATE TABLE CLEANER (
    EMPLOYEEID INT PRIMARY KEY,
    CONSTRAINT FK_CLEANER FOREIGN KEY (EMPLOYEEID) REFERENCES STRUCTURALEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE SHOPKEEPRS (
    EMPLOYEEID INT PRIMARY KEY,
    SHOPID INT,
    CONSTRAINT FK_SHOPKEEPERS FOREIGN KEY (EMPLOYEEID) REFERENCES STRUCTURALEMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_SHOPSHOPKEEPERS FOREIGN KEY (SHOPID) REFERENCES SHOPS(SHOPID)
);

CREATE TABLE TICKETSELLERS (
    EMPLOYEEID INT PRIMARY KEY,
    CONSTRAINT FK_TICKETSELLERS FOREIGN KEY (EMPLOYEEID) REFERENCES STRUCTURALEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE INSPECTORS (
    EMPLOYEEID INT PRIMARY KEY,
    CONSTRAINT FK_INSPECTORS FOREIGN KEY (EMPLOYEEID) REFERENCES STRUCTURALEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE CARETAKERS (
    EMPLOYEEID INT PRIMARY KEY,
    CONSTRAINT FK_CARETAKERS FOREIGN KEY (EMPLOYEEID) REFERENCES ANIMALEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE VETERINARIES (
	EMPLOYEEID INT PRIMARY KEY,
	CONSTRAINT FK_VETERINARIES FOREIGN KEY (EMPLOYEEID) REFERENCES ANIMALEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE GUIDEDENTRIES (
    TICKET_ID INT PRIMARY KEY NOT NULL,
    ROUTES_ID INT NOT NULL,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
    FOREIGN KEY (ROUTES_ID) REFERENCES ROUTES(ROUTEID),
);

CREATE TABLE EMPCON (
    EMPLOYEEID INT NOT NULL,
    CONTRACTID INT NOT NULL,
    BONUSPAY DECIMAL(6,2) NOT NULL DEFAULT '0.00',
    EXTRAHOURESPAY INT NOT NULL,
    CONSTRAINT FK_EMPCONEMP FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_EMPCONCON FOREIGN KEY (CONTRACTID) REFERENCES CONTRACTS(CONTRACTID),
    PRIMARY KEY (EMPLOYEEID, CONTRACTID)
);

CREATE TABLE SECGUA (
    EMPLOYEEID INT,
    SECTIONID INT,
    ACCIDENTDATE DATE NOT NULL,
    ACCIDENTCOST INT NOT NULL,
    CONSTRAINT FK_SECGUAEMP FOREIGN KEY (EMPLOYEEID) REFERENCES SECURITYEMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_SECGUASEC FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID),
    PRIMARY KEY (EMPLOYEEID, SECTIONID)
);

CREATE TABLE WEAPONLICENCES (
    WEAPONLICENCEID INT PRIMARY KEY,
    EMPLOYEEID INT,
    WEAPONNAME VARCHAR(20) NOT NULL,
    CONSTRAINT FK_EMPLOYEEID FOREIGN KEY (EMPLOYEEID) REFERENCES SECURITYEMPLOYEES(EMPLOYEEID)
);

CREATE TABLE WEAPON (
    WEAPONID INT PRIMARY KEY,
    WEAPONLICENCESID INT,
    CONSTRAINT FK_WEAPONLICENCES FOREIGN KEY (WEAPONLICENCESID) REFERENCES WEAPONLICENCES(WEAPONLICENCEID)
);

CREATE TABLE SECSUR (
    EMPLOYEEID INT,
    SECTIONID INT,
    ACCIDENTDATE DATE NOT NULL,
    ACCIDENTCOST INT NOT NULL,
    CONSTRAINT FK_SECSUREMP FOREIGN KEY (EMPLOYEEID) REFERENCES SECURITYEMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_SECSURSEC FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID),
    PRIMARY KEY (EMPLOYEEID, SECTIONID)
);

CREATE TABLE SECCLEA (
    EMPLOYEEID INT, 
    SECTIONID INT,
    ACCIDENTDATE DATE NOT NULL,
    ACCIDENTCOST INT NOT NULL,
    CONSTRAINT FK_SECCLEEMP FOREIGN KEY (EMPLOYEEID) REFERENCES STRUCTURALEMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_SECCLESEC FOREIGN KEY (SECTIONID) REFERENCES SECTIONS(SECTIONID),
    PRIMARY KEY (EMPLOYEEID, SECTIONID)
);

CREATE TABLE ANIVET (
    INTERVETIONID INT PRIMARY KEY,
    ANIMALID INT,
    EMPLOYEEID INT,
    COSTOFTREATMENT INT NOT NULL,
    CONSTRAINT FK_ANIVETEMP FOREIGN KEY (EMPLOYEEID) REFERENCES ANIMALEMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_ANIVETANI FOREIGN KEY (ANIMALID) REFERENCES ANIMALS(ANIMALID),
);

CREATE TABLE STUDIES (
    EMPLOYEEID INT,
    STUDIES VARCHAR(100) NOT NULL,
    CONSTRAINT FK_STUDIES FOREIGN KEY (EMPLOYEEID) REFERENCES VETERINARIES(EMPLOYEEID)
);

CREATE TABLE GUIROU (
    ROUTESID INT,
    EMPLOYEEID INT,
    CONSTRAINT FK_GUIROUEMP FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID),
    CONSTRAINT FK_GUIROUROU FOREIGN KEY (ROUTESID) REFERENCES ROUTES(ROUTEID),
    PRIMARY KEY (ROUTESID, EMPLOYEEID)
);

CREATE TABLE ENCINS (
    ENCLOSUREID CHAR(5),
    EMPLOYEEID INT,
    DATENEXTINSPECTION DATE NOT NULL,
    DATELASTINSPECTION DATE NOT NULL,
    CONSTRAINT FK_ENCINSEMP FOREIGN KEY (EMPLOYEEID) REFERENCES CARETAKERS(EMPLOYEEID),
    CONSTRAINT FK_ENCINSENC FOREIGN KEY (ENCLOSUREID) REFERENCES ENCLOSURES(ENCLOSUREID),
    PRIMARY KEY (ENCLOSUREID, EMPLOYEEID)
);

CREATE TABLE ENCCAR (
    ENCLOSUREID CHAR(5),
    EMPLOYEEID INT,
    CONSTRAINT FK_ENCCAREMP FOREIGN KEY (EMPLOYEEID) REFERENCES CARETAKERS(EMPLOYEEID),
    CONSTRAINT FK_ENCCARENC FOREIGN KEY (ENCLOSUREID) REFERENCES ENCLOSURES(ENCLOSUREID),
    PRIMARY KEY (ENCLOSUREID, EMPLOYEEID)
);

CREATE TABLE SPECIES (
    ENCLOSUREID CHAR(5) PRIMARY KEY,
    SPECIES VARCHAR(100) NOT NULL,
    CONSTRAINT FK_SPECIESENC FOREIGN KEY (ENCLOSUREID) REFERENCES ENCLOSURES(ENCLOSUREID)
);
GO
